#!/usr/bin/env bash


if [ "$1" == "" ]; then
  echo "We no longer have a default image. Please specify a coffea image."
  echo "Good choices would be:"
  echo " - coffeateam/coffea-dask-almalinux8:latest (for coffea CalVer)"
  echo " - coffeateam/coffea-base-almalinux8:latest (for coffea 0.7)"
  echo "All options can be enumerated by looking at either"
  echo " https://hub.docker.com/repositories/coffeateam"
  echo "or"
  echo " ls /cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam"
  exit 1
else
  export COFFEA_IMAGE=$1
fi

export APPTAINER_BINDPATH=/uscmst1b_scratch,/cvmfs,/cvmfs/grid.cern.ch/etc/grid-security:/etc/grid-security,/etc/condor/config.d/01_cmslpc_interactive,/usr/local/bin/cmslpc-local-conf.py:/usr/local/bin/cmslpc-local-conf.py.orig,.cmslpc-local-conf:/usr/local/bin/cmslpc-local-conf.py

APPTAINER_SHELL=$(which bash) apptainer exec -B ${PWD}:/srv --pwd /srv \
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/${COFFEA_IMAGE} \
  /bin/bash --rcfile /srv/.bashrc
